params:
  seed: 42

  # environment wrapper clipping
  env:
    # added to the wrapper
    clip_observations: 20.0
    # can make custom wrapper?
    clip_actions: 1.0

  algo:
    name: sac

  model:
    name: soft_actor_critic

  # doesn't have this fine grained control but made it close
  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None

        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 256]
      activation: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None
    log_std_bounds: [-20, 2]

  load_checkpoint: False # flag which sets whether to load the checkpoint
  load_path: '' # path to the checkpoint to load

  config:
    name: cartpole_decoupled
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    mixed_precision: False
    normalize_input: False
    normalize_value: False
    num_warmup_steps: 100
    num_actors: -1  # configured from the script (based on num_envs)
    normalize_advantage: True
    gamma: 0.99
    alpha_lr: 0.005
    actor_lr: 0.0003
    critic_lr: 0.0003
    critic_tau: 0.005
    num_steps_per_episode: 1  # How many env steps before the next gradient step
    max_epochs: 5000000       # total number of steps = num_steps_per_episode * max_epochs
    save_best_after: 100
    save_frequency: 20_000
    batch_size: 4096
    reward_shaper:
      scale_value: 1.0
    init_alpha: 1.0
    learnable_temperature: true
    replay_buffer_size: 1_000_000
    max_env_steps: 1000     # How many steps the environment can make at most
